# Generated by Django 5.2.4 on 2025-07-31 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='blogpics/')),
                ('text_1', models.TextField(blank=True, max_length=500, null=True)),
                ('picture_2', models.ImageField(blank=True, null=True, upload_to='blogpics/')),
                ('text_2', models.TextField(blank=True, max_length=500, null=True)),
                ('note_title', models.CharField(blank=True, max_length=200, null=True)),
                ('mini_pic_1', models.ImageField(blank=True, null=True, upload_to='blogpics/')),
                ('mini_pic_2', models.ImageField(blank=True, null=True, upload_to='blogpics/')),
                ('mini_pic_3', models.ImageField(blank=True, null=True, upload_to='blogpics/')),
                ('final_note_title', models.CharField(blank=True, max_length=200, null=True)),
                ('final_note_text', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalNoteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(max_length=200)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='home.blog')),
            ],
        ),
        migrations.CreateModel(
            name='TableTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
            ],
        ),
        migrations.CreateModel(
            name='TableTitleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('TableTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tabletitle')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='home.blog')),
            ],
        ),
    ]
