# Generated by Django 5.2.4 on 2025-07-31 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_finalnoteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletitleinfo',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='home.blog'),
        ),
    ]
