# Generated by Django 5.2.4 on 2025-07-31 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tabletitle_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletitleinfo',
            name='TableTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='home.tabletitle'),
        ),
    ]
